// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "lvcamctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CLvcamctrl1

IMPLEMENT_DYNCREATE(CLvcamctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLvcamctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CLvcamctrl1 operations
